[package]
name = "kbd"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
std = { path = "../std" }
tar-no-std = "0.1.8"
lazy_static = { "version" = "1.0", "features" = ["spin_no_std"] }
